### ISSUE TITLE
Loss problem

### ISSUE THREAD

**Issue by nemo0526** [ninatu/everything_at_once#7]
Hello! May I ask that what exactly the six positive samples and negative samples in your Combinatorial Loss ?

**Comment by ninatu** [comment]
Hi! 

We don’t have 6 positives. Our loss is called combinatorial since it leverages all combinations of modalities (six combinations in our case: loss between video and audio modalities, loss between video and text modalities, loss between video and fused audio-text, etc.). Let’s consider the loss of one combination, for example, the loss between video and audio. We consider negative samples inside a batch. For a batch size of 2240, for each video embedding, we have one positive audio embedding (audio from the same video clip) and 2239 negative audio embeddings. And the same is for audio — for each audio embedding, we have one positive video embedding (video from the same video clip)  and 2239 negative video embeddings. And the same for all other combinations of modalities.
